### PR TITLE
Fix #16 - Integration tests suite

### LINKED ISSUE #16: Move integration tests to a suite
And move integration tests to package `test`

### PR DESCRIPTION
**Pull request by cyrilc-pro**
Does not work yet, but let's see if the test suite matches our needs...

### CODE REVIEW

**Comment by ttetzlaff** [comment]
Should there be any changes to go.yml? We could change the `go test` to run tests in the `commands` folder and the integration tests to use `test` folder. But I'm not sure it is really any better this way.

**Comment by cyrilc-pro** [comment]
OK, thanks. So I'll continue this way.

**Comment by cyrilc-pro** [comment]
Some drawbacks of the test suite:
* Containers are shared so we have possible side-effects between unrelated tests
* Having nested tests is a bit more difficult

**Comment by cyrilc-pro** [comment]
Let's skip this test suite solution: too many drawbacks, not enough advantages.

**Pull request closed without merging**
